language: node_js
node_js:
    - "0.10"

branches:
    only:
        - master
        - dev

install:
    - npm install grunt-cli coveralls
    - npm install

cache:
    directories:
        - node_modules

script:
    - ./node_modules/.bin/grunt build testci
    #- cat ./test/result/lcov.info | ./node_modules/.bin/coveralls
